apiVersion: v1
kind: Service
metadata:
  name: day-29-service
  namespace: day-29
spec:
  type: NodePort
  selector:
    app: day-29
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30029