apiVersion: apps/v1
kind: Deployment
metadata:
  name: day26-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day26-app
  template:
    metadata:
      labels:
        app: day26-app
    spec:
      containers:
      - name: day26-app
        image: artenisal/day_26:0.0.1
        ports:
        - containerPort: 8000