apiVersion: apps/v1
kind: Deployment
metadata:
  name: day-27-deployment
  namespace: day-27
spec:
  replicas: 2
  selector:
    matchLabels:
      app: day-27
  template:
    metadata:
      labels:
        app: day-27
    spec:
      containers:
      - name: hello-world
        image: artenisal/day_26:0.0.1
        ports:
        - containerPort: 8000