apiVersion: v1
kind: Service
metadata:
  name: day-27-service
  namespace: day-27
spec:
  type: NodePort
  selector:
    app: day-27
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30027