name: Day 2 Python Check 

on:
  push:
    branches:
      - main # Trigger on pushes to the Day-2 branch

jobs:
  run-day2:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4 # Check out the repository
      - uses: actions/setup-python@v5 # Set up Python
        with:
          python-version: "3.11" # Specify Python version

      - run: python day-2/day-2.py # Run the Day 2 Python script
